name: Build and deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
     steps:
      - uses: actions/checkout@v2
      - name: Set environment variable
        run: echo "REACT_APP_GOOGLE_BOOKS_API_KEY=${{ secrets.GOOGLE_BOOKS_API_KEY }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@5.0.0
        with:
          branch: gh-pages
          folder: build
        env:
          REACT_APP_GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
